# Generated by Django 5.1.2 on 2024-10-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('background_image', models.ImageField(null=True, upload_to='sections/')),
                ('section', models.CharField(choices=[('products', 'Produkte'), ('features', 'Features'), ('about', 'Über Uns'), ('contact', 'Kontakt')], max_length=10, unique=True)),
            ],
        ),
    ]
