# Generated by Django 5.1.2 on 2024-10-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subtitle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
