# Generated by Django 5.1.2 on 2024-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_image_page_images_page_card_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='card_image',
        ),
        migrations.AddField(
            model_name='product',
            name='card_image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
