# Generated by Django 5.1.2 on 2024-10-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_images_page_image_remove_page_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_image_for_product', to='main.image'),
        ),
    ]
