# Generated by Django 5.1.2 on 2024-10-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_page_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.AddField(
            model_name='feature',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
